### ISSUE TITLE
Training files

### ISSUE THREAD

**Issue by triplewy** [frotms/Chinese-and-Western-Food-Classification#1]
Is it possible for you to include your training files and how you were able to achieve top-1 70% accuracy?

**Comment by frotms** [comment]
> Is it possible for you to include your training files and how you were able to achieve top-1 70% accuracy?

Now you'll see training files in [labels](https://github.com/frotms/Chinese-and-Western-Food-Classification/tree/master/labels). Just enjoy it! @triplewy

**Comment by triplewy** [comment]
Thank you!

**Comment by triplewy** [comment]
Also, is there any way to download the chinesefoodnet dataset? I checked their website but the link doesn't work anymore? Many thanks again!

**Comment by bopeng87** [comment]
I need this dataset too, would really appreciate it if a download link can be provided.  Thanks~

**Comment by frotms** [comment]
#2

**Comment by frotms** [comment]
#2

**Comment by frotms** [comment]
@triplewy what's your email?

**Comment by triplewy** [comment]
alex@lemonbox.me Thank you!

**Comment by sherlockzym** [comment]
logiczym@outlook.com Thank you!
